START TRANSACTION; 
  ALTER TABLE "user" ADD "password" CHARACTER VARYING NOT NULL DEFAULT '1234';
  ALTER TABLE "user" ADD "email" CHARACTER VARYING NOT NULL DEFAULT '@';
  ALTER TABLE "user" ADD CONSTRAINT user_email UNIQUE (email); 
COMMIT;